name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      day:
        description: "What's the day of the week?"
        required: true
        default: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Sherif on selected day"
        if : ${{ inputs.day == 'Friday' }}
        run: echo "$Greeting $First_Name. Today is ${{ inputs.day }}!"
        env:
          First_Name: Sherif
