name: Read File Example

on: push

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v3

      - name: 📂 Read and print message.txt
        run: cat data/message.txt

      - name: 📥 Read file into variable
        id: read_file
        run: |
          {
            echo "CONTENT<<EOF"
            cat data/message.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: 📤 Print content from variable
        run: |
          echo "File content is: ${{ steps.read_file.outputs.CONTENT }}"
