name: Notify Repo A

on:
  push:
    branches:
      - main   
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to Repo A
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_A_TOKEN }}" \
            https://api.github.com/repos/OWNER/REPO_A/dispatches \
            -d '{"event_type":"trigger-release"}'
